include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 100
  trailing_commas: preserve

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - 'lib/generated/**'
    - 'build/**'
    - '**/*.mocks.dart'

  errors:
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    parameter_assignments: ignore

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disable overly strict rules for template project
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false

    # Keep these enabled
    always_use_package_imports: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_web_libraries_in_flutter: true
    directives_ordering: true
    sort_constructors_first: true
    unawaited_futures: true
    avoid_js_rounded_ints: false
    cascade_invocations: false
    flutter_style_todos: false
