// Mocks generated by Mockito 5.4.4 from annotations
// in kairos/test/features/journal/domain/usecases/delete_thread_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kairos/core/utils/result.dart' as _i4;
import 'package:kairos/features/journal/domain/entities/journal_thread_entity.dart'
    as _i5;
import 'package:kairos/features/journal/domain/repositories/journal_thread_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JournalThreadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalThreadRepository extends _i1.Mock
    implements _i2.JournalThreadRepository {
  MockJournalThreadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.JournalThreadEntity>> createThread(
          _i5.JournalThreadEntity? thread) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThread,
          [thread],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.JournalThreadEntity>>.value(
            _i6.dummyValue<_i4.Result<_i5.JournalThreadEntity>>(
          this,
          Invocation.method(
            #createThread,
            [thread],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.JournalThreadEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.JournalThreadEntity?>> getThreadById(
          String? threadId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThreadById,
          [threadId],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.JournalThreadEntity?>>.value(
            _i6.dummyValue<_i4.Result<_i5.JournalThreadEntity?>>(
          this,
          Invocation.method(
            #getThreadById,
            [threadId],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.JournalThreadEntity?>>);

  @override
  _i3.Stream<List<_i5.JournalThreadEntity>> watchThreadsByUserId(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchThreadsByUserId,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i5.JournalThreadEntity>>.empty(),
      ) as _i3.Stream<List<_i5.JournalThreadEntity>>);

  @override
  _i3.Future<_i4.Result<void>> updateThread(_i5.JournalThreadEntity? thread) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThread,
          [thread],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateThread,
            [thread],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> archiveThread(String? threadId) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveThread,
          [threadId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #archiveThread,
            [threadId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> syncThreads(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncThreads,
          [userId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #syncThreads,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteThread(String? threadId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteThread,
          [threadId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteThread,
            [threadId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);
}
