// Mocks generated by Mockito 5.4.4 from annotations
// in kairos/test/features/journal/domain/services/journal_upload_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i7;

import 'package:kairos/core/services/firebase_storage_service.dart' as _i2;
import 'package:kairos/core/utils/result.dart' as _i5;
import 'package:kairos/features/journal/domain/entities/journal_message_entity.dart' as _i9;
import 'package:kairos/features/journal/domain/repositories/journal_message_repository.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirebaseStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorageService extends _i1.Mock implements _i2.FirebaseStorageService {
  MockFirebaseStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String buildJournalPath({
    required String? userId,
    required String? journalId,
    required String? filename,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildJournalPath,
          [],
          {
            #userId: userId,
            #journalId: journalId,
            #filename: filename,
          },
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #buildJournalPath,
            [],
            {
              #userId: userId,
              #journalId: journalId,
              #filename: filename,
            },
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i5.Result<String>> uploadFile({
    required _i6.File? file,
    required String? storagePath,
    required _i2.FileType? fileType,
    Map<String, String>? metadata,
    int? imageMaxSize,
    int? imageQuality,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #file: file,
            #storagePath: storagePath,
            #fileType: fileType,
            #metadata: metadata,
            #imageMaxSize: imageMaxSize,
            #imageQuality: imageQuality,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i4.Future<_i5.Result<String>>.value(_i3.dummyValue<_i5.Result<String>>(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #file: file,
              #storagePath: storagePath,
              #fileType: fileType,
              #metadata: metadata,
              #imageMaxSize: imageMaxSize,
              #imageQuality: imageQuality,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<String>>);

  @override
  _i4.Future<_i5.Result<_i7.Uint8List>> generateThumbnail(
    _i6.File? imageFile, {
    int? size = 150,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateThumbnail,
          [imageFile],
          {#size: size},
        ),
        returnValue:
            _i4.Future<_i5.Result<_i7.Uint8List>>.value(_i3.dummyValue<_i5.Result<_i7.Uint8List>>(
          this,
          Invocation.method(
            #generateThumbnail,
            [imageFile],
            {#size: size},
          ),
        )),
      ) as _i4.Future<_i5.Result<_i7.Uint8List>>);

  @override
  _i4.Future<_i5.Result<void>> deleteFile(String? downloadUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [downloadUrl],
        ),
        returnValue: _i4.Future<_i5.Result<void>>.value(_i3.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #deleteFile,
            [downloadUrl],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [JournalMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalMessageRepository extends _i1.Mock implements _i8.JournalMessageRepository {
  MockJournalMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<_i9.JournalMessageEntity>> createMessage(
          _i9.JournalMessageEntity? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMessage,
          [message],
        ),
        returnValue: _i4.Future<_i5.Result<_i9.JournalMessageEntity>>.value(
            _i3.dummyValue<_i5.Result<_i9.JournalMessageEntity>>(
          this,
          Invocation.method(
            #createMessage,
            [message],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i9.JournalMessageEntity>>);

  @override
  _i4.Future<_i5.Result<_i9.JournalMessageEntity?>> getMessageById(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageById,
          [messageId],
        ),
        returnValue: _i4.Future<_i5.Result<_i9.JournalMessageEntity?>>.value(
            _i3.dummyValue<_i5.Result<_i9.JournalMessageEntity?>>(
          this,
          Invocation.method(
            #getMessageById,
            [messageId],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i9.JournalMessageEntity?>>);

  @override
  _i4.Stream<List<_i9.JournalMessageEntity>> watchMessagesByThreadId(String? threadId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMessagesByThreadId,
          [threadId],
        ),
        returnValue: _i4.Stream<List<_i9.JournalMessageEntity>>.empty(),
      ) as _i4.Stream<List<_i9.JournalMessageEntity>>);

  @override
  _i4.Future<_i5.Result<void>> updateMessage(_i9.JournalMessageEntity? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [message],
        ),
        returnValue: _i4.Future<_i5.Result<void>>.value(_i3.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #updateMessage,
            [message],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> syncMessages(String? threadId) => (super.noSuchMethod(
        Invocation.method(
          #syncMessages,
          [threadId],
        ),
        returnValue: _i4.Future<_i5.Result<void>>.value(_i3.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #syncMessages,
            [threadId],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> syncThreadIncremental(String? threadId) => (super.noSuchMethod(
        Invocation.method(
          #syncThreadIncremental,
          [threadId],
        ),
        returnValue: _i4.Future<_i5.Result<void>>.value(_i3.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #syncThreadIncremental,
            [threadId],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<List<_i9.JournalMessageEntity>>> getPendingUploads(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingUploads,
          [userId],
        ),
        returnValue: _i4.Future<_i5.Result<List<_i9.JournalMessageEntity>>>.value(
            _i3.dummyValue<_i5.Result<List<_i9.JournalMessageEntity>>>(
          this,
          Invocation.method(
            #getPendingUploads,
            [userId],
          ),
        )),
      ) as _i4.Future<_i5.Result<List<_i9.JournalMessageEntity>>>);
}
